name: CI
"on":
  push:
    branches:
      - main
      - fix/**
      - feature/**
  pull_request:
    branches:
      - main
permissions:
  contents: read
jobs:
  build-and-test:
    runs-on: macos-26
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
      - name: Swift version
        run: swift --version
      - name: Build (debug)
        run: swift build
      - name: Run unit tests
        run: swift test
      - name: Build (release)
        run: swift build -c release
      - name: Run acceptance tests
        run: bash AcceptanceTests/runner.sh .build/release/try
      - uses: SonarSource/sonarqube-scan-action@22918119ff8e1ca75a623e15c8296b6ea4fbe28f # v8.2.1
        name: SonarQube Analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
